name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: bartek
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/enigo-wp/wp-content/themes/enigo
            git pull

